### ISSUE TITLE
create a binary analysis mode 

### ISSUE THREAD

**Issue by needmorecowbell** [needmorecowbell/Hamburglar#5]
example hamburglar.py -b <file or directory>

this should take the input file and create a hexdump of it (https://www.geoffreybrown.com/blog/a-hexdump-program-in-python/)

After making the hexdump, the dump should be checked for signatures to check for misnamed and/or embedded files in the input. (https://www.garykessler.net/library/file_sigs.html)

**Comment by adi928** [comment]
Hi, for the file signatures recognition feature, would it be a good idea to include a database, scraped from the linked page, to this repo?
Also, I was able to do the first part of this enhancement [here](https://github.com/adi928/Hamburglar/commit/f9d5626c99752ab427d0f7c0c26d0fa190b62672). Appreciate any feedback.

**Comment by needmorecowbell** [comment]
Thanks a ton for your contributions, and nice idea on how to do the hex dump, I like it a lot. One thing I'd do differently is change the flag to something other than -file. Maybe -b isn't the best flag for it, maybe the flag could be `hamburglar.py --hexdump <file>`? I'm just trying to avoid ambiguity. 

Also, can you return the dump as a string? or have a separate method that returns just the unformatted hexdump? That way it can be used internally by hamburglar when looking for embedded files whenever that feature is added. The hexdump alone is a nice feature  though and I'd like to keep it!

I created the branch hamburglar lite today, and I think I'll change the documentation to denote that hamburglar lite will be a script that can run on python 2 or 3 with no external dependencies. Including database functionality would be a great addition to the main branch. I think either a central mysql database where everything gets aggregated is one way of handling it (check out my project sniff-paste to see what I mean), or have each query generate an sqllite db file for itself are the two approaches that could be taken to getting a database included. Two separate ways of handling this, I'm not sure which is best.

**Comment by adi928** [comment]
I went through the Gary Kessler page for file signatures and found that his table is not as properly formatted as that of Wikipedia's (which he references in his page). So would it be okay if we compare the file hex dump against those signatures? Otherwise, I think there is a lot of manual work involved in scraping through the former site. 
I have a [table scraper](https://github.com/adi928/Hamburglar/blob/master/tableScraper.py) ready in my forked project. I'm still working on converting everything to a string so that it is easier to compare.

**Comment by needmorecowbell** [comment]
Nice work! I feel like the hex signatures aren't going to change, so we don't really need to regularly pull from the wikipedia table, just updating it every once in a while to check for new/modified signatures would be enough. However you think is best though, the table scraper you made is looking good so far. Is using  toorroot what you're using as the mysql creds? Now that the project is getting bigger it might be a good idea to start adding config settings to a separate file. That way github auth and db creds can just be tailored there and doesn't have to be typed in/hardcoded each time. 

Having issues assigning you the issue for some reason but yeah absolutely I'll get that done once I figure it out!
