### ISSUE TITLE
create mode for scraping github (via org, user, or repo)

### ISSUE THREAD

**Issue by needmorecowbell** [needmorecowbell/Hamburglar#6]
Process (skip any level that's not included)...

get users from org (https://api.github.com/orgs/<orgname>/members)  ->
get repos from each user (https://api.github.com/users/<username>/repos)  ->
aggregate all repos to be analyzed and filtered in whatever way needed

So in this way, a whole organization could be checked, a user could be checked, or a repo could be checked. Analysis could scan through commit history, like trufflehog.

**Comment by adi928** [comment]
Hey, I'm planning to pick this up. The orgs which I come across in GitHub have URL without 'api' keyword. For example:

-  For Users - https://github.com/orgs/<orgName>/people
-  For repos from each user - https://github.com/<username>?tab=repositories

Is that what you are looking for?

**Comment by adi928** [comment]
It seems you have already developed Giggity for the same purpose 😄. Or am I missing something?

**Comment by needmorecowbell** [comment]
Hey! Yeah giggity is meant to tie into this issue, but it doesn't close it. I was thinking about including it as an import once I more fully develop the module. Giggity would handle the pulling of all the repo information available to us from github, but then hamburglar would be used to scan through all the commit history checking against the regex filters that are made. 

I wanted Giggity to just be used in the retrieval of tailored github api information, and hamburglar for further analysis. If you work on this issue, can you make a separate branch for it? I will need to change the readme and decide whether to make a lite version of the script that doesn't need imports.

**Comment by adi928** [comment]
Understood. As per contributing to this project, I have forked the repo and I believe I can generate a pull request from there when I'm done developing. So I think I'm alright if you make changes here.

**Comment by needmorecowbell** [comment]
For anyone reading this, you don't actually need --pickaxe-regex unless you're trying to use a regex to match against the log. Because hamburglar is doing this part, it's good enough to just do `git log -p` 

This issue is now solved as of https://github.com/needmorecowbell/Hamburglar/commit/a0c58977e62924ee1a1de32c6ea5cdfd2159e238
